---
title: "Social_Survey_And_Lakers"
author: "Mia Fitzgerald"
date: "4/7/2026"
output:
  html_document:
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)
library(tidyverse)
library(lubridate)
library(knitr)
library(forcats)

```


### Combining Levels


```{r}
gss1 <- gss_cat %>%
  mutate(marital = fct_recode(marital, 
"Pre-Marriage" = "Never married",
"Marriage" = "Married",
"Marriage" = "Separated",
"Post-Marriage" = "Divorced",
"Post-Marriage" = "Widowed",
"Missing" = "No answer"))

gss1 %>%
  count(marital) %>%
  kable()

```


^[Question 1 complete]


### Proportion of Responses in Each Year


```{r}
gss2 <- gss1 %>%
  count(year, marital) %>%
  group_by(year) %>%
  mutate(prop = n/sum(n))

gss2 %>%
  kable()

```


^[Question 2 complete]


### Staus Reordered by Year


```{r}
gss3 <- gss2 %>%
  group_by(year, marital) %>%
  arrange(desc(year), desc(prop)) %>%
  ungroup()

gss3 %>%
  kable()

```


^[Question 3 complete]


### Proportion Versus Year


```{r}
ggplot(gss3, aes(x = year, y = prop, color = marital)) + 
  geom_point() +
  geom_line()

```


^[Question 4 complete]


### Integer to Date Error


```{r}
lakers %>%
  mutate(new_date = make_date(date)) %>%
  select(date, new_date, time, player, result, etype, points) %>%
  head(n=6) %>%
  kable()

```


^[Question 5 complete]


### Subset of Dataset Including Parsed Dates


```{r}
lakers2 <- lakers %>%
  mutate(date2 = as.character(date)) %>%
  mutate(date2 = ymd(date2)) 

lakers2 %>%
  select(date, date2, team, etype, time, points) %>%
  head(6) %>%
  kable()

```


^[Question 6 complete]


### Games Played on Different Days of the Week


```{r}
lakers_bar <- lakers2 %>%
  distinct(date2) %>%
  mutate(day = wday(date2, label = TRUE, abbr = TRUE))

ggplot(lakers_bar, aes(day)) +
  geom_bar()

```


^[Question 7 complete]